Repository Keyneez/Keyneez-AOS, pull requests merged in 2023-01, with the labels that each got.

#4 [CHORE/#3] colors 및 font 세팅
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/keyneez/util/OnSingleClickListener.kt
  app/src/main/java/com/keyneez/util/extension/ViewExt.kt
  app/src/main/res/font/keyneez_font.xml
  app/src/main/res/font/pretendard_bold.otf
  app/src/main/res/font/pretendard_medium.otf
  app/src/main/res/font/pretendard_semibold.otf
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/styles.xml
  app/src/main/res/values/themes.xml
Labels: CHORE 🎀, Pull Request 🤗, 채연 🐸

#13 [CHORE/#11] font lineSpacingExtra 및 letterSpacing 설정
  app/src/main/res/values/styles.xml
Labels: CHORE 🎀, Pull Request 🤗, 채연 🐸

#12 [FEAT/#10] main bottomnavi 구현
  app/build.gradle
  app/src/main/java/com/keyneez/presentation/card/CardFragment.kt
  app/src/main/java/com/keyneez/presentation/character/CharacterFragment.kt
  app/src/main/java/com/keyneez/presentation/home/HomeFragment.kt
  app/src/main/java/com/keyneez/presentation/home/HomeViewModel.kt
  app/src/main/java/com/keyneez/presentation/like/LikeFragment.kt
  app/src/main/java/com/keyneez/presentation/main/MainActivity.kt
  app/src/main/java/com/keyneez/presentation/setting/SettingFragment.kt
  app/src/main/res/drawable/ic_like_baseline.xml
  app/src/main/res/drawable/ic_like_edit.xml
  app/src/main/res/drawable/ic_like_search.xml
  app/src/main/res/drawable/ic_main_carddown.xml
  app/src/main/res/drawable/ic_main_cardup.xml
  app/src/main/res/drawable/ic_main_character.xml
  app/src/main/res/drawable/ic_main_home.xml
  app/src/main/res/drawable/ic_main_like.xml
  app/src/main/res/drawable/ic_main_setting.xml
  app/src/main/res/drawable/img_home_logo.xml
  app/src/main/res/drawable/sel_main_bottomnavi.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_card.xml
  app/src/main/res/layout/fragment_character.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_like.xml
  app/src/main/res/layout/fragment_setting.xml
  app/src/main/res/menu/main_menu.xml
  app/src/main/res/values/strings.xml
Labels: FEAT ✨, Pull Request 🤗, 동주 🦦

#8 [UI/#5] like / UI 작업
  app/src/main/java/com/keyneez/presentation/character/CharacterFragment.kt
  app/src/main/java/com/keyneez/presentation/main/MainActivity.kt
  app/src/main/java/com/keyneez/presentation/main/character/CharacterFragment.kt
  app/src/main/java/com/keyneez/presentation/main/home/HomeFragment.kt
  app/src/main/java/com/keyneez/presentation/main/home/HomeViewModel.kt
  app/src/main/java/com/keyneez/presentation/main/id/IdFragment.kt
  app/src/main/java/com/keyneez/presentation/main/like/LikeFragment.kt
  app/src/main/java/com/keyneez/presentation/main/setting/SettingFragment.kt
  app/src/main/res/drawable/ic_like_baseline.xml
  app/src/main/res/drawable/img_like_background.png
  app/src/main/res/drawable/shape_14_rect.xml
  app/src/main/res/layout/fragment_character.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_id.xml
  app/src/main/res/layout/fragment_like.xml
  app/src/main/res/layout/fragment_setting.xml
  app/src/main/res/layout/item_like_content.xml
  app/src/main/res/values/strings.xml
Labels: Pull Request 🤗, UI 💄, 지은 🐭

#16 [FEAT/#6] like / 저장 탭 구현 완료
  app/src/main/java/com/keyneez/data/entity/LikeData.kt
  app/src/main/java/com/keyneez/presentation/main/like/LikeAdapter.kt
  app/src/main/java/com/keyneez/presentation/main/like/LikeFragment.kt
  app/src/main/java/com/keyneez/presentation/main/like/LikeViewModel.kt
  app/src/main/res/drawable/shape_14_rect.xml
  app/src/main/res/layout/item_like_content.xml
  app/src/main/res/values/strings.xml
Labels: FEAT ✨, Pull Request 🤗, UI 💄, 지은 🐭

#18 [UI/#9] ocr / ocr 뷰 구현
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/keyneez/presentation/main/MainActivity.kt
  app/src/main/java/com/keyneez/presentation/ocr/OcrActivity.kt
  app/src/main/java/com/keyneez/presentation/ocr/OcrViewModel.kt
  app/src/main/java/com/keyneez/presentation/ocr/guide/OcrGuideActivity.kt
  app/src/main/java/com/keyneez/presentation/ocr/guide/OcrGuideAdapter.kt
  app/src/main/java/com/keyneez/presentation/ocr/guide/complete/OcrCompleteFragment.kt
  app/src/main/java/com/keyneez/presentation/ocr/guide/guide/OcrGuideFragment.kt
  app/src/main/java/com/keyneez/util/binding/BindingAdapter.kt
  app/src/main/java/com/keyneez/util/custom/HorizontalCardFrameView.kt
  app/src/main/java/com/keyneez/util/custom/VerticalCardFrameView.kt
  app/src/main/res/drawable/ic_ocr_camera_btn.xml
  app/src/main/res/drawable/ic_ocr_close.xml
  app/src/main/res/drawable/ic_ocr_complete_detail.xml
  app/src/main/res/drawable/ic_ocr_guide_back.xml
  app/src/main/res/drawable/ic_ocr_switch_horizontal.xml
  app/src/main/res/drawable/ic_ocr_switch_vertical.xml
  app/src/main/res/drawable/img_dummy.png
  app/src/main/res/drawable/img_ocr_complete_card_dummy.png
  app/src/main/res/drawable/img_ocr_complete_jelly_dummy.png
  app/src/main/res/drawable/img_ocr_guide_card.xml
  app/src/main/res/drawable/sel_ocr_switch.xml
  app/src/main/res/drawable/shape_gray900_fill_4_rect.xml
  app/src/main/res/layout/activity_ocr.xml
  app/src/main/res/layout/activity_ocr_guide.xml
  app/src/main/res/layout/fragment_ocr_complete.xml
  app/src/main/res/layout/fragment_ocr_guide.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
Labels: Pull Request 🤗, UI 💄, 채연 🐸

#31 [UI/#28] test complete, ocr / bottom sheet dialog 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/keyneez/presentation/login/LoginActivity.kt
  app/src/main/java/com/keyneez/presentation/ocr/OcrActivity.kt
  app/src/main/java/com/keyneez/presentation/ocr/dialog/OcrResultFragment.kt
  app/src/main/java/com/keyneez/presentation/ocr/dialog/OcrResultViewModel.kt
  app/src/main/java/com/keyneez/presentation/signup/SignupActivity.kt
  app/src/main/java/com/keyneez/presentation/signup/test/complete/TestCompleteFragment.kt
  app/src/main/java/com/keyneez/util/binding/BindingBottomSheetDialog.kt
  app/src/main/res/drawable/ic_auto_login_result_edit.xml
  app/src/main/res/drawable/img_jelly_description_dummy.xml
  app/src/main/res/drawable/sel_ocr_result_confirm_btn.xml
  app/src/main/res/drawable/sel_ocr_result_id_type.xml
  app/src/main/res/drawable/shape_gray050_fill_gray900_line_5_rect.xml
  app/src/main/res/drawable/shape_gray100_fill_8_rect.xml
  app/src/main/res/drawable/shape_gray900_fill_5_rect.xml
  app/src/main/res/layout/bot_sheet_jelly_description.xml
  app/src/main/res/layout/bot_sheet_ocr_result.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: Pull Request 🤗, UI 💄, 채연 🐸

#19 [UI/#14] onboarding 뷰 레이아웃 구현
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/keyneez/presentation/login/LoginAdapter.kt
  app/src/main/java/com/keyneez/presentation/login/pin/LoginPinFragment.kt
  app/src/main/java/com/keyneez/presentation/ocr/guide/OcrGuideActivity.kt
  app/src/main/java/com/keyneez/presentation/ocr/guide/complete/OcrCompleteFragment.kt
  app/src/main/java/com/keyneez/presentation/ocr/guide/guide/OcrGuideFragment.kt
  app/src/main/java/com/keyneez/presentation/onboarding/OnFirstFragment.kt
  app/src/main/java/com/keyneez/presentation/onboarding/OnFourthFragment.kt
  app/src/main/java/com/keyneez/presentation/onboarding/OnSecondFragment.kt
  app/src/main/java/com/keyneez/presentation/onboarding/OnThirdFragment.kt
  app/src/main/java/com/keyneez/presentation/onboarding/OnboardingActivity.kt
  app/src/main/java/com/keyneez/presentation/onboarding/OnboardingAdapter.kt
  app/src/main/java/com/keyneez/presentation/onboarding/OnboardingViewModel.kt
  app/src/main/java/com/keyneez/presentation/signup/SignupAdapter.kt
  app/src/main/java/com/keyneez/presentation/signup/pin/SignupPinFragment.kt
  app/src/main/java/com/keyneez/presentation/signup/pin/SignupPinViewModel.kt
  app/src/main/java/com/keyneez/presentation/signup/pin/confirm/SignupPinConfirmFragment.kt
  app/src/main/res/drawable/ic_main_card_down.xml
  app/src/main/res/drawable/ic_main_card_up.xml
  app/src/main/res/drawable/ic_onboarding_logo.xml
  app/src/main/res/drawable/ic_signup_pin_erase.xml
  app/src/main/res/drawable/img_home_logo.xml
  app/src/main/res/drawable/img_onboarding_1.xml
  app/src/main/res/drawable/img_onboarding_2.xml
  app/src/main/res/drawable/img_onboarding_3.xml
  app/src/main/res/drawable/img_onboarding_4.xml
  app/src/main/res/drawable/sel_pin_circle.xml
  app/src/main/res/drawable/shape_gray050_gary900line_4_rect.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_onboarding.xml
  app/src/main/res/layout/fragment_login_pin.xml
  app/src/main/res/layout/fragment_on_first.xml
  app/src/main/res/layout/fragment_on_fourth.xml
  app/src/main/res/layout/fragment_on_second.xml
  app/src/main/res/layout/fragment_on_third.xml
  app/src/main/res/layout/fragment_signup_pin.xml
  app/src/main/res/layout/fragment_signup_pin_confirm.xml
  app/src/main/res/values/strings.xml
Labels: Pull Request 🤗, UI 💄, 동주 🦦

#24 [UI/#20] info detail 레이아웃 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/keyneez/presentation/main/detail/DetailActivity.kt
  app/src/main/java/com/keyneez/presentation/main/detail/DetailViewModel.kt
  app/src/main/res/drawable/ic_detail_arrowback.xml
  app/src/main/res/drawable/ic_detail_forward.xml
  app/src/main/res/drawable/ic_detail_heart.xml
  app/src/main/res/drawable/ic_detail_share.xml
  app/src/main/res/drawable/img_detail_background.png
  app/src/main/res/drawable/sel_detail_heart.xml
  app/src/main/res/drawable/shape_gray050_fill_gary900_line_4_rect.xml
  app/src/main/res/drawable/shape_gray800_fill_100_rect.xml
  app/src/main/res/layout/activity_home_detail.xml
  app/src/main/res/layout/activity_onboarding.xml
  app/src/main/res/values/strings.xml
Labels: Pull Request 🤗, UI 💄, 동주 🦦

#37 [CHORE/#35] 서버 기초 세팅
  app/src/main/java/com/keyneez/data/model/response/wrapper/BaseResponse.kt
  app/src/main/java/com/keyneez/data/repository/ContentRepository.kt
  app/src/main/java/com/keyneez/data/repository/ContentRepositoryImpl.kt
  app/src/main/java/com/keyneez/data/repository/UserRepository.kt
  app/src/main/java/com/keyneez/data/repository/UserRepositoryImpl.kt
  app/src/main/java/com/keyneez/data/service/ContentService.kt
  app/src/main/java/com/keyneez/data/service/UserService.kt
  app/src/main/java/com/keyneez/data/source/ContentDataSource.kt
  app/src/main/java/com/keyneez/data/source/UserDataSource.kt
  app/src/main/java/com/keyneez/di/RepositoryModule.kt
  app/src/main/java/com/keyneez/di/ServiceModule.kt
  app/src/main/res/values/strings.xml
Labels: CHORE 🎀, Pull Request 🤗, 채연 🐸

#41 [FEAT/#40] 다날 유저 생성 서버 통신 구현
  app/build.gradle
  app/src/main/java/com/keyneez/data/model/request/RequestPostDanalSignupDto.kt
  app/src/main/java/com/keyneez/data/model/response/ResponsePostDanalSignupDto.kt
  app/src/main/java/com/keyneez/data/repository/UserRepository.kt
  app/src/main/java/com/keyneez/data/repository/UserRepositoryImpl.kt
  app/src/main/java/com/keyneez/data/service/UserService.kt
  app/src/main/java/com/keyneez/data/source/UserDataSource.kt
  app/src/main/java/com/keyneez/di/RetrofitModule.kt
  app/src/main/java/com/keyneez/presentation/login/LoginActivity.kt
  app/src/main/java/com/keyneez/presentation/login/phone/PhoneFragment.kt
  app/src/main/java/com/keyneez/presentation/login/phone/PhoneViewModel.kt
  app/src/main/java/com/keyneez/presentation/main/id/IdFragment.kt
  app/src/main/java/com/keyneez/presentation/main/id/IdPhotoActivity.kt
  app/src/main/java/com/keyneez/presentation/ocr/guide/complete/OcrCompleteFragment.kt
  app/src/main/java/com/keyneez/presentation/onboarding/OnFourthFragment.kt
  app/src/main/java/com/keyneez/presentation/onboarding/OnSecondFragment.kt
  app/src/main/java/com/keyneez/presentation/onboarding/OnThirdFragment.kt
  app/src/main/java/com/keyneez/presentation/signup/SignupActivity.kt
  app/src/main/java/com/keyneez/presentation/signup/danal/guide/DanalGuideFragment.kt
  app/src/main/java/com/keyneez/presentation/signup/danal/guide/DanalGuideViewModel.kt
  app/src/main/java/com/keyneez/util/UiState.kt
  app/src/main/res/layout/fragment_danal_guide.xml
  app/src/main/res/values/strings.xml
Labels: FEAT ✨, Pull Request 🤗, 채연 🐸

#47 [FEAT/#45] signup / danal 부분 변경
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/keyneez/data/model/response/ResponseGetContentDeatilDto.kt
  app/src/main/java/com/keyneez/data/repository/ContentRepository.kt
  app/src/main/java/com/keyneez/data/repository/ContentRepositoryImpl.kt
  app/src/main/java/com/keyneez/data/service/ContentService.kt
  app/src/main/java/com/keyneez/data/source/ContentDataSource.kt
  app/src/main/java/com/keyneez/presentation/main/detail/DetailActivity.kt
  app/src/main/java/com/keyneez/presentation/main/detail/DetailViewModel.kt
  app/src/main/java/com/keyneez/presentation/signup/danal/guide/DanalGuideViewModel.kt
  app/src/main/res/layout/activity_home_detail.xml
  app/src/main/res/layout/fragment_danal_guide.xml
  app/src/main/res/values/strings.xml
Labels: FEAT ✨, Pull Request 🤗, 동주 🦦

#50 [UI/#33] main / bottomnavi custom layout 추가
  app/src/main/java/com/keyneez/util/custom/CustomBottomNavView.kt
  app/src/main/java/com/keyneez/util/custom/RoundedBottomNavigationView.kt
  app/src/main/java/com/keyneez/util/extension/dpToPx.kt
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_home_recommend.xml
  app/src/main/res/layout/fragment_like.xml
  app/src/main/res/layout/fragment_setting.xml
Labels: Pull Request 🤗, UI 💄, 동주 🦦

#48 [Feat/#36] detail 서버 연결
  app/src/main/java/com/keyneez/data/model/response/ResponseGetContentDeatilDto.kt
  app/src/main/java/com/keyneez/presentation/main/detail/DetailActivity.kt
  app/src/main/java/com/keyneez/util/binding/BindingAdapter.kt
  app/src/main/res/layout/activity_home_detail.xml
Labels: FEAT ✨, Pull Request 🤗, 동주 🦦

#53 [FEAT/#39] login / 로그인 서버 통신 구현
  app/src/main/java/com/keyneez/presentation/login/LoginActivity.kt
  app/src/main/java/com/keyneez/presentation/login/LoginViewModel.kt
  app/src/main/java/com/keyneez/presentation/login/phone/PhoneFragment.kt
  app/src/main/java/com/keyneez/presentation/login/pin/LoginPinFragment.kt
  app/src/main/java/com/keyneez/presentation/login/pin/LoginPinViewModel.kt
  app/src/main/java/com/keyneez/presentation/signup/danal/guide/DanalGuideFragment.kt
  app/src/main/java/com/keyneez/presentation/signup/pin/SignupPinFragment.kt
  app/src/main/java/com/keyneez/presentation/signup/pin/confirm/SignupPinConfirmFragment.kt
  app/src/main/res/values/strings.xml
Labels: FEAT ✨, Pull Request 🤗, 채연 🐸

#54 [FEAT/#46] ocr / Google ML Kit OCR 기능 구현
  app/build.gradle
  app/src/main/java/com/keyneez/data/model/response/ResponseIdDto.kt
  app/src/main/java/com/keyneez/presentation/login/phone/PhoneFragment.kt
  app/src/main/java/com/keyneez/presentation/login/pin/LoginPinFragment.kt
  app/src/main/java/com/keyneez/presentation/main/id/IdFragment.kt
  app/src/main/java/com/keyneez/presentation/ocr/OcrActivity.kt
  app/src/main/java/com/keyneez/presentation/ocr/OcrViewModel.kt
  app/src/main/java/com/keyneez/presentation/ocr/dialog/OcrResultFragment.kt
  app/src/main/java/com/keyneez/presentation/ocr/dialog/OcrResultViewModel.kt
  app/src/main/java/com/keyneez/presentation/signup/danal/guide/DanalGuideFragment.kt
  app/src/main/java/com/keyneez/util/binding/BindingAdapter.kt
  app/src/main/res/layout/bot_sheet_ocr_result.xml
  app/src/main/res/layout/fragment_danal_guide.xml
  app/src/main/res/layout/fragment_id.xml
  app/src/main/res/layout/fragment_login_pin.xml
  app/src/main/res/layout/item_like_content.xml
  build.gradle
Labels: FEAT ✨, Pull Request 🤗, 채연 🐸

#55 [FEAT/#38] home / server connect
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/keyneez/data/model/request/RequestPostSaveDto.kt
  app/src/main/java/com/keyneez/data/model/response/ResponseContentDto.kt
  app/src/main/java/com/keyneez/data/repository/ContentRepository.kt
  app/src/main/java/com/keyneez/data/repository/ContentRepositoryImpl.kt
  app/src/main/java/com/keyneez/data/service/ContentService.kt
  app/src/main/java/com/keyneez/data/source/ContentDataSource.kt
  app/src/main/java/com/keyneez/presentation/main/detail/DetailActivity.kt
  app/src/main/java/com/keyneez/presentation/main/detail/DetailViewModel.kt
  app/src/main/java/com/keyneez/presentation/main/home/HomeFragment.kt
  app/src/main/java/com/keyneez/presentation/main/home/recommend/RecommendAdapter.kt
  app/src/main/java/com/keyneez/presentation/main/home/recommend/RecommendFragment.kt
  app/src/main/java/com/keyneez/presentation/main/home/recommend/RecommendViewModel.kt
  app/src/main/java/com/keyneez/presentation/main/like/LikeAdapter.kt
  app/src/main/java/com/keyneez/presentation/main/search/SearchAdapter.kt
  app/src/main/java/com/keyneez/util/binding/BindingAdapter.kt
  app/src/main/res/drawable/shape_gray050_80_fill_gray050_line_rect.xml
  app/src/main/res/layout/activity_home_detail.xml
  app/src/main/res/layout/activity_id_photo.xml
  app/src/main/res/layout/activity_ocr.xml
  app/src/main/res/layout/fragment_home_recommend.xml
  app/src/main/res/layout/item_home.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: FEAT ✨, Pull Request 🤗, 동주 🦦

#58 [FEAT/#46] ocr, main / ocr 및 바텀 네비게이션 이슈 해결
  app/build.gradle
  app/src/main/java/com/keyneez/data/model/request/RequestPostStudentUserCheckDto.kt
  app/src/main/java/com/keyneez/data/model/request/RequestPostYouthUserCheckDto.kt
  app/src/main/java/com/keyneez/data/model/response/ResponsePostUserCheckDto.kt
  app/src/main/java/com/keyneez/data/repository/UserRepository.kt
  app/src/main/java/com/keyneez/data/repository/UserRepositoryImpl.kt
  app/src/main/java/com/keyneez/data/service/UserService.kt
  app/src/main/java/com/keyneez/data/source/UserDataSource.kt
  app/src/main/java/com/keyneez/presentation/main/MainActivity.kt
  app/src/main/java/com/keyneez/presentation/main/MainViewModel.kt
  app/src/main/java/com/keyneez/presentation/ocr/OcrActivity.kt
  app/src/main/java/com/keyneez/presentation/ocr/OcrViewModel.kt
  app/src/main/java/com/keyneez/presentation/ocr/dialog/OcrResultFragment.kt
  app/src/main/java/com/keyneez/presentation/ocr/dialog/OcrResultViewModel.kt
  app/src/main/java/com/keyneez/util/custom/CustomBottomNavView.kt
  build.gradle
Labels: FEAT ✨, Pull Request 🤗, 채연 🐸

#60 [FEAT/#59] splash 화면 생성
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/keyneez/presentation/main/home/HomeFragment.kt
  app/src/main/java/com/keyneez/presentation/main/home/popular/PopularFragment.kt
  app/src/main/java/com/keyneez/presentation/main/home/popular/PopularViewModel.kt
  app/src/main/java/com/keyneez/presentation/main/home/recent/NewFragment.kt
  app/src/main/java/com/keyneez/presentation/main/home/recent/NewViewModel.kt
  app/src/main/java/com/keyneez/presentation/splash/SplashActivity.kt
  app/src/main/res/drawable/ic_splash_bottom.xml
  app/src/main/res/drawable/img_splash_logo.png
  app/src/main/res/layout/activity_splash.xml
  app/src/main/res/layout/fragment_home.xml
Labels: FEAT ✨, Pull Request 🤗, 동주 🦦

#62 ADD/#57 signup / 코드 이것저것 추가
  app/src/main/java/com/keyneez/presentation/main/MainActivity.kt
  app/src/main/java/com/keyneez/presentation/main/like/LikeFragment.kt
  app/src/main/res/drawable/img_sign_up_board.png
  app/src/main/res/drawable/img_sign_up_book.png
  app/src/main/res/drawable/img_sign_up_glasses.png
  app/src/main/res/drawable/img_sign_up_hat.png
  app/src/main/res/drawable/img_sign_up_headset.png
  app/src/main/res/drawable/img_sign_up_money.png
  app/src/main/res/drawable/img_sign_up_ring.png
  app/src/main/res/drawable/img_sign_up_telescope.png
  app/src/main/res/drawable/img_sign_up_tie.png
  app/src/main/res/drawable/img_sign_up_wing.png
  app/src/main/res/values/strings.xml
Labels: ADD ➕, Pull Request 🤗, 지은 🐭

#64 [ADD/#61] logo 추가
  app/src/debug/ic_launcher-playstore.png
  app/src/debug/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/debug/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/src/debug/res/mipmap-hdpi/ic_launcher.png
  app/src/debug/res/mipmap-hdpi/ic_launcher_foreground.png
  app/src/debug/res/mipmap-hdpi/ic_launcher_round.png
  app/src/debug/res/mipmap-mdpi/ic_launcher.png
  app/src/debug/res/mipmap-mdpi/ic_launcher_foreground.png
  app/src/debug/res/mipmap-mdpi/ic_launcher_round.png
  app/src/debug/res/mipmap-xhdpi/ic_launcher.png
  app/src/debug/res/mipmap-xhdpi/ic_launcher_foreground.png
  app/src/debug/res/mipmap-xhdpi/ic_launcher_round.png
  app/src/debug/res/mipmap-xxhdpi/ic_launcher.png
  app/src/debug/res/mipmap-xxhdpi/ic_launcher_foreground.png
  app/src/debug/res/mipmap-xxhdpi/ic_launcher_round.png
  app/src/debug/res/mipmap-xxxhdpi/ic_launcher.png
  app/src/debug/res/mipmap-xxxhdpi/ic_launcher_foreground.png
  app/src/debug/res/mipmap-xxxhdpi/ic_launcher_round.png
  app/src/debug/res/values/ic_launcher_background.xml
Labels: ADD ➕, 동주 🦦

#63 [MOD/#46] 레이아웃 보완 및 예외 처리
  app/src/main/java/com/keyneez/presentation/main/detail/DetailActivity.kt
  app/src/main/java/com/keyneez/presentation/main/detail/DetailViewModel.kt
  app/src/main/java/com/keyneez/presentation/ocr/dialog/OcrResultFragment.kt
  app/src/main/java/com/keyneez/presentation/ocr/dialog/OcrResultViewModel.kt
  app/src/main/res/drawable/img_test_complete_jelly_dummy.png
  app/src/main/res/layout/activity_home_detail.xml
  app/src/main/res/layout/activity_splash.xml
  app/src/main/res/layout/fragment_test_complete.xml
  app/src/main/res/layout/item_home.xml
  app/src/main/res/values/strings.xml
Labels: MOD ✅, Pull Request 🤗, 채연 🐸

#65 [FEAT/#38] 홈 카드 색 변화 바인딩 어댑터 적용
  app/src/main/java/com/keyneez/util/binding/BindingAdapter.kt
Labels: FEAT ✨, Pull Request 🤗, 동주 🦦

#67 [MOD/#66] like search layout
  app/src/main/res/layout/item_like_content.xml
  app/src/main/res/layout/item_search_content.xml
  app/src/main/res/values/colors.xml
Labels: MOD ✅, Pull Request 🤗, 동주 🦦

#73 Feature/#69 qa
  app/src/main/res/layout/activity_home_detail.xml
  app/src/main/res/layout/activity_search.xml
Labels: FIX 🔨, 동주 🦦
